name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Download deps
      run: |
        wget --output-document=gotestsum.tgz https://github.com/gotestyourself/gotestsum/releases/download/v0.3.5/gotestsum_0.3.5_linux_amd64.tar.gz
        tar xzf gotestsum.tgz
        rm -f gotestsum.tgz
    - name: Test and Build
      uses: docker://golang:1-stretch
      with:
        args: ./gotestsum --jsonfile tests-reports.json  -- -count=1 -coverprofile coverage-sonar.out -coverpkg=./... ./...
      env:
        XDG_CACHE_HOME: /tmp/.cache
        HOME: /tmp/buildhome
            
