name: Build

on: [push]

jobs:
    
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download deps
      run: |
        wget --output-document=gotestsum.tgz https://github.com/gotestyourself/gotestsum/releases/download/v0.3.5/gotestsum_0.3.5_linux_amd64.tar.gz
        tar xzf gotestsum.tgz
        rm -f gotestsum.tgz
    - name: Test
      uses: docker://golang:1-stretch
      with:
        args: ./gotestsum --jsonfile tests-reports.json  -- -count=1 -coverprofile coverage-sonar.out -coverpkg=./... ./...
      env:
        XDG_CACHE_HOME: /tmp/.cache
        HOME: /tmp/buildhome
        
  build:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
    - uses: actions/checkout@v1
    - name: Build
      uses: docker://golang:1-stretch
      with:
        args: go build ./cmd/tdt2go
      env:
        XDG_CACHE_HOME: /tmp/.cache
        HOME: /tmp/buildhome
        CGO_ENABLED: 0
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: tdt2go-bin
        path: ./tdt2go
